### PR TITLE
Fixed error with missing defaultLanguage

### PR DESCRIPTION
**Pull request by dennisobrien**
In the previous changes to adapt numbro.js to fit with Bokeh, I missed this undefined variable `defaultLanguage`.  (PyCharm tried to warn me.)  The code path I was testing did not pass a `language` argument so I didn't discover this.  But other code paths that call `format` do pass a `language` argument, causing a JavaScript exception.

This change looks for a `language` parameter and call `numbro.setCulture(language)` if a value is passed.

Note that since Numbro.js forked from Numeral.js, they changed from the idea of a language (really a country code, such as "en" or "es") to a culture (really a locale, such as "en-US" or "es-ES").  This means code that passed languages that were listed in the NumeralLanguage enum but were not locales (e.g., "de", "fr") would fall back to use the locale "en-US". This may be more of a breaking change than we want to introduce.  Or we add shim code to accept invalid language codes and transform them to the most common locale fit.

### CODE REVIEW

**Comment by damianavila** [comment]
ping @mistakevin :wink: (IIRC, you were working with @dennisobrien on this numbro...

**Comment by dennisobrien** [comment]
I was just testing other values for `language` to the formatter in Bokeh 0.10.0 and it looks like anything other than "en" results in a JavaScript error.

```
from bokeh.io import output_notebook
output_notebook()

from bokeh.enums import NumeralLanguage
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, TableColumn, NumberFormatter
from ipywidgets import interact
import numpy as np
import pandas as pd

@interact(locale=NumeralLanguage._values)
def display_table_with_locale(locale='en'):
    df = pd.DataFrame(
        data=[
            [1, 2, 3], 
            [1,2,3], 
            [10000, 20000, 30000]
        ], 
        columns=['x', 'y', 'z']
    )
    source = ColumnDataSource(df)
    columns = [
        TableColumn(field='x', title='x', formatter=NumberFormatter(format="$0,.0", language=locale)),
        TableColumn(field='y', title='y', formatter=NumberFormatter(format="$0,.0", language=locale)),
        TableColumn(field='z', title='z', formatter=NumberFormatter(format="$0,.0", language=locale)), 
    ]
    data_table = DataTable(source=source, columns=columns, editable=False)

    show(data_table)

display_table_with_locale()
```

The JavaScript error that results from any language other than "en":

```
Uncaught TypeError: Cannot read property 'delimiters' of undefined
```

So maybe the situation with this PR (other locales seem to behave as "en-US") is better than the behavior in 0.10.0 and can be addressed in further PR.

**Comment by dennisobrien** [comment]
@mistakevin -- I meant to propose this PR for 'bokeh' branch instead of the 'develop' branch.  Not sure how that went wrong.

If you don't have the time to merge this into the 'bokeh' branch, I could change the other PR to use my branch:

```
    "numbro": "git://github.com/dennisobrien/numbro.git#72ef9cf0",
```

**Comment by kevincolten** [comment]
Pulled against `bokeh` branch in https://github.com/bokeh/numbro/pull/2

**Pull request closed without merging**
