### PR TITLE
removed some methods used in node mode

### PR DESCRIPTION
**Pull request by dennisobrien**
I am revisiting some issues in Bokeh that can be fixed by using numbro.  When I tried using the previous version of bokeh/numbro (git://github.com/bokeh/numbro.git#c30487b) I saw some new errors in the runtime.

`Error: Cannot find module 'fs'`

I'm not sure how this requirement is getting picked up (since it is in an uncalled function) but it has to be due to these Node related functions.

This change removes those node functions.
- numbro.includeLocalesInNode
- numbro.loadLanguagesInNode
- numbro.loadCulturesInNode

### CODE REVIEW

**Comment by dennisobrien** [comment]
@mistakevin - Is this something you could help with?  I need this merged into the bokeh branch of this fork so I can link to it from a bokeh PR.

Let me know if I can provide any more context.

thanks,
Dennis

**Comment by bryevdv** [comment]
ping @mattpap can you help with this PR and the related PR?

**Comment by mattpap** [comment]
@dennisobrien, what version of node and npm do you use? It's likely you have to use node 4 and compatible with it version of npm (2 I presume).

**Comment by dennisobrien** [comment]
Hi Matt,

I'm on Ubuntu 15.04 and using Chris Lea's PPA to get node and npm.  That said, my versions are not as late as you mentioned.

```
$ nodejs --version
v0.10.37
$ npm --version
1.4.28
```

If I need to update these in order to build bokehjs I will try that.  But I'm not sure what happens in the build process that would have lead to the error.  When I built bokehjs and used bokeh/numbro.git#c30487b (the version before this PR) instead of Numeral.js, I got a runtime js error "cannot find module 'fs'".  I thought the most expedient fix was to prune these methods from the bokeh fork of numbro (we have already done some extensive pruning), but if building bokeh with updated node/npm will work, I can try that.  But I believe 'fs' is filesystem utilities for node, not useful in a javascript browser runtime.

If we wanted to have all the locale functionality from numbro, it might be worth keeping these methods and figuring out how to make it work, but AFAIK language/locale functionality never worked with the Numeral.js shipped with bokeh.  (It's been a while since I tested this, so I could be wrong.)

Let me know what you think.  I'll try to find some time tonight to test a bokeh build using numbro.git#c30487b with updated node/npm.  If that is the route we take, the bokeh build should be updated to fail on older versions of node/npm, because they will be introducing a runtime bug.

thanks,
Dennis

**Comment by bryevdv** [comment]
@mattpap any objections to merging this as-is for now?

**Comment by kevincolten** [comment]
I'm sure this is known, but you will have to update the commit hash [here](https://github.com/bokeh/bokeh/pull/3883/files#diff-3a70afdf73d2ab402f406c8a90df9b93R48) when this is merged

**Comment by dennisobrien** [comment]
In this PR in progress, I'm currently referencing my own branch of bokeh/numbro.
https://github.com/bokeh/bokeh/pull/3883/files#diff-3a70afdf73d2ab402f406c8a90df9b93R48

Once this PR is accepted (assuming it is okay) I will update to use the commit hash from this repo, then work on moving that PR forward.

@mattpap - I have not yet had a chance to update node and npm and test with that.  I'll try to get some time this weekend.  But I'm hoping we can just remove those unused methods as is.

**Comment by bryevdv** [comment]
Agree `fs` should only be useful in Node though we are slowly trying to get most of BokehJS to run in Node, so maybe it's (slightly) better to keep them if possible. If that does fix, agreed should make an issue to mandate minimum requirements. But if that does not fix, I think we can go ahead and merge this.

**Comment by mattpap** [comment]
> I'm not sure how this requirement is getting picked up (since it is in an uncalled function) (...)

Actually it is called and numbro confuses browserify node-like environment with node.js.

EDIT: see line #1205 in `numbro.js` and then implementation of `inNodejsRuntime()`. Now I wonder how this PR works, it should fail with `undefined is not a function`.

**Comment by mattpap** [comment]
It looks like browserify doesn't shim `fs` module by default (as it does with e.g. `process`). It still should fail at module resolution time, not runtime. Anyway, I think we can remove this code and proceed with this PR, just make sure to remove all related code (line 1205 and `inNodejsRuntime()`).

**Comment by bryevdv** [comment]
> remove all related code (line 1205 and `inNodejsRuntime()`).

Just to be clear you mean these two:

https://github.com/bokeh/numbro/blob/develop/numbro.js#L1015-L1019
https://github.com/bokeh/numbro/blob/develop/numbro.js#L1205

correct? @dennisobrien once you remove those I'll get this merged.

**Comment by mattpap** [comment]
@bryevdv, yes.

**Comment by dennisobrien** [comment]
From what I understand, the changes were being made to the "bokeh" branch of bokeh/numbro.  I don't know the purposes of "develop" versus "bokeh", but the last time we touched this, the commit hash we used was from the "bokeh" branch.

So I will remove the method inNodejsRuntime:
https://github.com/bokeh/numbro/blob/bokeh/numbro.js#L937-L941

But the call to `numbro.loadCulturesInNode('languages')` was already removed from the "bokeh" branch of bokeh/numbro.

Sorry if this is confusing.  I don't know what the standard way to work with a fork like this is.

**Comment by dennisobrien** [comment]
Hmm, I made the change to remove `inNodejsRuntime` but now there is a conflict.  I don't have write access to deal with the merge conflict.  @mattpap -- can you assist with this?

**Comment by dennisobrien** [comment]
BTW, I get a build error trying to build the latest snapshot of bokeh using nodejs v5.6.0 and npm v3.6.0.  Unable to find module '_process'.  First I got the error on my development branch 'dennisobrien/fix/2922_use_numbrojs_take_4', but I get the same error building from the latest from bokeh master.  Maybe nodejs v5.6.0 is too bleeding edge.  I'll try with nodejs v4.x next.

```
python setup.py install

Bokeh includes a JavaScript library (BokehJS) that has its own
build process. How would you like to handle BokehJS:

1) build and install fresh BokehJS
2) install last built BokehJS from bokeh/bokehjs/build

Choice? 1
Building BokehJS... Failed.

ERROR: 'gulp build' returned the following

---- on stdout:
    [00:07:07] Using gulpfile ~/workspace/bokeh/bokehjs/gulpfile.js
    [00:07:07] Starting 'build'...
    [00:07:07] Starting 'scripts'...
    [00:07:07] Starting 'scripts:coffee'...
    [00:07:07] Starting 'scripts:eco'...
    [00:07:07] Starting 'styles'...
    [00:07:07] Starting 'styles:build'...
    [00:07:08] Finished 'scripts:eco' after 1.46 s
    [00:07:09] Finished 'styles:build' after 2.79 s
    [00:07:09] Starting 'styles:minify'...
    [00:07:09] Finished 'styles:minify' after 109 ms
    [00:07:09] Finished 'styles' after 2.9 s
    [00:07:11] Finished 'scripts:coffee' after 4.47 s
    [00:07:11] Starting 'scripts:compile'...
    [00:07:11] Finished 'scripts:compile' after 2.98 s
    [00:07:11] Starting 'scripts:build'...


---- on stderr:
    /home/dennis/workspace/bokeh/bokehjs/node_modules/resolve/lib/sync.js:33
        throw new Error("Cannot find module '" + x + "' from '" + y + "'");
        ^

    Error: Cannot find module '_process' from '/home/dennis/workspace/bokeh/bokehjs/node_modules/coffee-script/lib/coffee-script'
      at Function.module.exports [as sync] (/home/dennis/workspace/bokeh/bokehjs/node_modules/resolve/lib/sync.js:33:11)
      at DestroyableTransform._transform (/home/dennis/workspace/bokeh/bokehjs/gulp/labeler.coffee:33:25)
      at DestroyableTransform.Transform._read (/home/dennis/workspace/bokeh/bokehjs/node_modules/readable-stream/lib/_stream_transform.js:172:10)
      at DestroyableTransform.Transform._write (/home/dennis/workspace/bokeh/bokehjs/node_modules/readable-stream/lib/_stream_transform.js:160:12)
      at Labeled.Pipeline._write (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:73:22)
      at doWrite (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:279:12)
      at writeOrBuffer (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:266:5)
      at Labeled.Writable.write (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:211:11)
      at Labeled.ondata (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:572:20)
      at emitOne (events.js:90:13)
      at Labeled.emit (events.js:182:7)
      at readableAddChunk (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:195:16)
      at Labeled.Readable.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at Labeled.Pipeline._read (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:57:31)
      at DestroyableTransform.onreadable (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:64:18)
      at DestroyableTransform.g (events.js:273:16)
      at emitNone (events.js:80:13)
      at DestroyableTransform.emit (events.js:179:7)
      at emitReadable_ (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:456:10)
      at emitReadable (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:450:7)
      at readableAddChunk (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:206:11)
      at DestroyableTransform.Readable.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at DestroyableTransform.Transform.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at DestroyableTransform._transform (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/index.js:664:14)
      at DestroyableTransform.Transform._read (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
      at DestroyableTransform.Transform._write (/home/dennis/workspace/bokeh/bokehjs/node_modules/browserify/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
      at Labeled.Pipeline._write (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:73:22)
      at doWrite (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:279:12)
      at writeOrBuffer (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:266:5)
      at Labeled.Writable.write (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:211:11)
      at Labeled.ondata (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:572:20)
      at emitOne (events.js:90:13)
      at Labeled.emit (events.js:182:7)
      at readableAddChunk (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:195:16)
      at Labeled.Readable.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at Labeled.Pipeline._read (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:57:31)
      at DestroyableTransform.onreadable (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:64:18)
      at DestroyableTransform.g (events.js:273:16)
      at emitNone (events.js:80:13)
      at DestroyableTransform.emit (events.js:179:7)
      at emitReadable_ (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_readable.js:456:10)
      at emitReadable (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_readable.js:450:7)
      at readableAddChunk (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_readable.js:206:11)
      at DestroyableTransform.Readable.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_readable.js:162:10)
      at DestroyableTransform.Transform.push (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_transform.js:145:32)
      at /home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/index.js:76:16
      at Array.forEach (native)
      at sorter (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/index.js:67:14)
      at DestroyableTransform.end [as _flush] (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/index.js:14:9)
      at DestroyableTransform.<anonymous> (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_transform.js:135:12)
      at DestroyableTransform.g (events.js:273:16)
      at emitNone (events.js:80:13)
      at DestroyableTransform.emit (events.js:179:7)
      at prefinish (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_writable.js:450:12)
      at finishMaybe (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_writable.js:458:7)
      at endWritable (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_writable.js:469:3)
      at DestroyableTransform.Writable.end (/home/dennis/workspace/bokeh/bokehjs/node_modules/deps-sort/node_modules/readable-stream/lib/_stream_writable.js:436:5)
      at Labeled.<anonymous> (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/index.js:46:26)
      at Labeled.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at Labeled.emit (events.js:179:7)
      at finishMaybe (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:460:14)
      at endWritable (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:469:3)
      at Labeled.Writable.end (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_writable.js:436:5)
      at Labeled.onend (/home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:537:10)
      at Labeled.g (events.js:273:16)
      at emitNone (events.js:85:20)
      at Labeled.emit (events.js:179:7)
      at /home/dennis/workspace/bokeh/bokehjs/node_modules/stream-splicer/node_modules/readable-stream/lib/_stream_readable.js:934:16
      at nextTickCallbackWith0Args (node.js:453:9)
      at process._tickDomainCallback (node.js:423:13)
```

**Comment by dennisobrien** [comment]
I just verified that I get the same error `Error: Cannot find module 'fs'` when building my bugfix branch with nodejs v4.3.1 and npm v2.14.12.  That is, my fork dennisobrien/bokeh branch dennisobrien/fix/2922_use_numbrojs_take_4, but using this version of bokeh/numbro before this PR.

Previously I was using nodejs v0.10.37 and npm v1.4.28.  So I don't think the nodejs version was the culprit.

**Comment by mattpap** [comment]
@dennisobrien, so I was comparing this PR to `develop` (the default branch), which caused some confusion. We should change the default branch to `bokeh`. This PR is LGTM.

**Comment by mattpap** [comment]
> I just verified that I get the same error `Error: Cannot find module 'fs'` (...)

I'm not sure what's the underlying cause for the different behavior on different systems, but there is PR https://github.com/bokeh/bokeh/pull/3911 that is supposed to "fix" the problem. Make sure to try it out, so that I get confirmation it helps the issue.

**Comment by bryevdv** [comment]
@dennisobrien I am not sure what is going on with the branches or conflict. I created a team for this repo with write access and invited you. Then you should be able to resolve whatever you need to here. If you are interested, we should probably just discuss adding you to @bokeh/dev soon.

**Pull request merged**
